added examples to EXTRA_DIST

diff --git a/projects/codecs/C/configure b/projects/codecs/C/configure
--- a/projects/codecs/C/configure
+++ b/projects/codecs/C/configure
@@ -2219,7 +2219,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=rlglue_codec_c
- VERSION=1.0-alpha
+ VERSION=1.0-alpha-1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3628,7 +3628,7 @@ _ACEOF
   LIBS="-lrlgluenetdev $LIBS"
 
 else
-  echo "You must have RL-Glue installed to use this codec.  We could not find the RL-Glue library.  If you have not downloaded it please see http://glue.rl-community.org/. If RL-Glue is not in a standard location please do ./configure LDFLAGS=-L/path/to/rlglue/glue/libs"; exit 1
+  echo "You must have RL-Glue installed to use this codec.  We could not find the RL-Glue library.  If you have not downloaded it please see http://glue.rl-community.org/. If RL-Glue is not in a standard location please do ./configure LDFLAGS=-L/path/to/rlglue/glue/lib"; exit 1
 fi
 
 ac_ext=c
